[workspace]
authors = ["Gaelle Loutfi <gaelleloutfi31@gmail.com>"]
channels = ["conda-forge"]
name = "Petit Projet 1 images MNIST digits modifiees"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.3.*"
numpy = ">=2.3.3,<3"
pandas = ">=2.3.2,<3"
matplotlib = ">=3.10.6,<4"
tensorflow = ">=2.18.0,<3"
scikit-learn = ">=1.7.2,<2"
jupyter = ">=1.1.1,<2"
